export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMITED = 'RATE_LIMITED',
  UPLOAD_VERIFICATION_FAILED = 'UPLOAD_VERIFICATION_FAILED',
  STORAGE_UNAVAILABLE = 'STORAGE_UNAVAILABLE',
  SETTING_INVALID = 'SETTING_INVALID',
  INTERNAL = 'INTERNAL',
}
